org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.16.5
minecraft_version_range=[1.16.5,1.17)
forge_version=36.2.34
forge_version_range=[36,)
loader_version_range=[36,)

mapping_channel=official
mapping_version=1.16.5

mod_id=lightbridges
mod_name=PortalMod-ules: Light Bridges
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=io.github.bengman.lightbridges
mod_authors=Ben G Man
mod_description=Example mod description.\nNewline characters can be used and will be replaced properly.
